services:
  db:
    image: mysql:8.0
    container_name: DB
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: hanjinpl
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  backend:
    image: hanjinpl/webapp/backend
    container_name: Backend
    restart: unless-stopped
    ports:
      - 3002:3002
    volumes:
      - ./backend/dist:/app/dist
      
  frontend:
    image: hanjinpl/webapp/frontend
    container_name: Frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend/build:/app/build
