# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

run-name: Dev branch pull시 React App build 및 Github Pages로 배포

on:
  pull_request:
    branches: [ "dev-bananamilk" ]
    types: [ closed ]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: set git config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config -l

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'prototype-one'

    strategy:
      matrix:
        node-version: [ 22.4.1 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'prototype-one/package-lock.json'
    - run: npm ci
    - run: npm run deploy
